# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12e89fb9618effa9e217148406de23685dcceaa00b2c74db2e96d03ec2d13f6513331b88b953b2c34fac6069c9b9149345ce0632812f10bff26119ac338e3ba2

test:
  secret_key_base: e6b394f72ccb7c8ceecb6981843833c084884b44155dfdaa0efe2390ddb9e5d0d64a07057b80e30caac606492e9c09c3cb9f5f582ac54827c2a8e906f105cec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
